"""feat: moved vendor status to vendor profile

Revision ID: 0d115ad20ee2
Revises: 61080c4e6ccf
Create Date: 2025-04-28 16:58:14.912532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d115ad20ee2'
down_revision = '61080c4e6ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('vendor_status')

    with op.batch_alter_table('vendor_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_profiles', schema=None) as batch_op:
        batch_op.drop_column('vendor_status')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
