"""fix: role in user

Revision ID: 1a8373f7efce
Revises: 7acaecf4b87f
Create Date: 2025-04-27 20:16:53.399420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a8373f7efce'
down_revision = '7acaecf4b87f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=True))
        batch_op.drop_column('roles')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_column('role')

    # ### end Alembic commands ###
