"""fix: enum to string for promotion type

Revision ID: 2c1897f923b6
Revises: 9e833f454a3a
Create Date: 2025-05-02 19:21:35.682874

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2c1897f923b6'
down_revision = '9e833f454a3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.alter_column('promotion_type',
               existing_type=postgresql.ENUM('PERCENTAGE_DISCOUNT', 'FIXED_DISCOUNT', 'FREE_SHIPPING', 'BUY_X_GET_Y', name='promotiontype'),
               type_=sa.String(length=25),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.alter_column('promotion_type',
               existing_type=sa.String(length=25),
               type_=postgresql.ENUM('PERCENTAGE_DISCOUNT', 'FIXED_DISCOUNT', 'FREE_SHIPPING', 'BUY_X_GET_Y', name='promotiontype'),
               existing_nullable=False)

    # ### end Alembic commands ###
