"""feat: removed target id in AdminLog

Revision ID: 3979de86d6ab
Revises: ca4c68ac400f
Create Date: 2025-04-25 19:54:31.464066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3979de86d6ab'
down_revision = 'ca4c68ac400f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_log', schema=None) as batch_op:
        batch_op.drop_column('target_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
