"""fix: removed is_vendor

Revision ID: 61080c4e6ccf
Revises: 1a8373f7efce
Create Date: 2025-04-27 20:36:55.502113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61080c4e6ccf'
down_revision = '1a8373f7efce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_vendor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_vendor', sa.BOOLEAN(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
