"""feat: roles in user

Revision ID: 7acaecf4b87f
Revises: f514d0422ac2
Create Date: 2025-04-27 20:09:51.736177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7acaecf4b87f'
down_revision = 'f514d0422ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roles', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('roles')

    # ### end Alembic commands ###
