"""feat: update testimonial

Revision ID: 8528f68c115c
Revises: e762b9043e50
Create Date: 2025-05-05 21:17:41.070125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8528f68c115c'
down_revision = 'e762b9043e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=2048), nullable=True))

    with op.batch_alter_table('vendor_testimonials', schema=None) as batch_op:
        batch_op.drop_constraint('vendor_testimonials_admin_id_fkey', type_='foreignkey')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor_testimonials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('vendor_testimonials_admin_id_fkey', 'admin_users', ['admin_id'], ['user_id'])

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
