"""fix: admin multiple relationship to user 2

Revision ID: b614d13f4116
Revises: e3808c4d75ea
Create Date: 2025-04-24 23:42:43.439835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b614d13f4116'
down_revision = 'e3808c4d75ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###
