"""feat: updated order table 
removed min order and added discount amount in association

Revision ID: ca8dd253a184
Revises: 2c1897f923b6
Create Date: 2025-05-02 22:44:53.021092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8dd253a184'
down_revision = '2c1897f923b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_order_association',
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('discount_applied', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('eligible_items', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('promotion_id', 'order_id')
    )
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.drop_column('min_order_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promotions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_order_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    op.drop_table('promotion_order_association')
    # ### end Alembic commands ###
