"""feat: removed granted by column in admin table

Revision ID: de571f67a599
Revises: bc9d5b62e3a7
Create Date: 2025-04-25 00:29:39.410384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de571f67a599'
down_revision = 'bc9d5b62e3a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.drop_constraint('admin_users_granted_by_fkey', type_='foreignkey')
        batch_op.drop_column('granted_by')
        batch_op.drop_column('granted_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('granted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('granted_by', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('admin_users_granted_by_fkey', 'users', ['granted_by'], ['id'])

    # ### end Alembic commands ###
