"""feat: promotion to category association

Revision ID: e762b9043e50
Revises: c19fe7f65b50
Create Date: 2025-05-04 23:41:50.242884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e762b9043e50'
down_revision = 'c19fe7f65b50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('promotion_category_association',
    sa.Column('promotion_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], ),
    sa.PrimaryKeyConstraint('promotion_id', 'category_id')
    )
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('promotion_category_association')
    # ### end Alembic commands ###
