"""fix: wishlist association

Revision ID: f4f7c1e026a5
Revises: 7fc06fb21374
Create Date: 2025-05-01 17:11:25.036738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f7c1e026a5'
down_revision = '7fc06fb21374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wishlist_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('wishlist_association_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'wishlists', ['wishlist_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wishlist_association', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('wishlist_association_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.drop_column('wishlist_id')

    # ### end Alembic commands ###
