"""feat: vendor profile

Revision ID: f514d0422ac2
Revises: 3979de86d6ab
Create Date: 2025-04-27 16:14:37.320130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f514d0422ac2'
down_revision = '3979de86d6ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=100), nullable=False),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('business_address', sa.String(length=200), nullable=True),
    sa.Column('business_phone', sa.String(length=20), nullable=True),
    sa.Column('business_email', sa.String(length=100), nullable=True),
    sa.Column('business_logo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('vendor_status')

    op.drop_table('vendor_profiles')
    # ### end Alembic commands ###
